require 'lib/stubs'
require 'models/skeleton/core/account'
require 'models/skeleton/core/user'
require 'models/skeleton/core/login'
require 'models/skeleton/core/timezone'
require 'models/skeleton/core/preference'

require 'models/skeleton/core/daily'
require 'models/skeleton/core/hourly'
require 'models/skeleton/core/minutely'

require 'models/skeleton/core/notification'
require 'models/skeleton/core/notificationopen'
require 'models/skeleton/core/notificationlink'
require 'models/skeleton/core/notificationclick'

require 'notifications/welcome'
require 'notifications/confirm'
require 'notifications/reset'
require 'notifications/youadded'
