-- Insert your seed data here.

-- zi_state
-- 
INSERT INTO public.zi_state (value) VALUES
	 ('CA'),
	 ('NH'),
	 ('OR'),
	 ('ND'),
	 ('TX'),
	 ('NV'),
	 ('KY'),
	 ('OH'),
	 ('NY'),
	 ('HI') on conflict do nothing;
INSERT INTO public.zi_state (value) VALUES
	 ('NM'),
	 ('MS'),
	 ('IN'),
	 ('DC'),
	 ('WV'),
	 ('NE'),
	 ('MO'),
	 ('FL'),
	 ('ME'),
	 ('AR') on conflict do nothing;
INSERT INTO public.zi_state (value) VALUES
	 ('CT'),
	 ('NC'),
	 ('WI'),
	 ('SD'),
	 ('RI'),
	 ('OK'),
	 ('ID'),
	 ('GA'),
	 ('MN'),
	 ('PA') on conflict do nothing;
INSERT INTO public.zi_state (value) VALUES
	 ('AK'),
	 ('MD'),
	 ('LA'),
	 ('WY'),
	 ('MT'),
	 ('IL'),
	 ('TN'),
	 ('NJ'),
	 ('MI'),
	 ('WA') on conflict do nothing;
INSERT INTO public.zi_state (value) VALUES
	 ('MA'),
	 ('UT'),
	 ('IA'),
	 ('VT'),
	 ('CO'),
	 ('SC'),
	 ('VA'),
	 ('DE'),
	 ('AZ'),
	 ('KS') on conflict do nothing;

-- zi_company_headcount
-- 
INSERT INTO public.zi_company_headcount (value) VALUES
	 ('1 to 10'),
	 ('501 to 1000'),
	 ('1001 to 5000'),
	 ('26 to 50'),
	 ('11 to 25'),
	 ('5001 to 10000'),
	 ('10000+'),
	 ('101 to 250'),
	 ('51 to 100'),
	 ('251 to 500') on conflict do nothing;

-- zi_company_revenue
-- 
INSERT INTO public.zi_company_revenue (value) VALUES
	 ('1 Billion and Over'),
	 ('10 Million to 25 Million'),
	 ('Under 1 Million'),
	 ('1 Million to 5 Million'),
	 ('25 Million to 50 Miliion'),
	 ('5 Million to 10 Million'),
	 ('50 Million to 100 Million'),
	 ('250 Million to 500 Million'),
	 ('500 Million to 1 Billion'),
	 ('100 Million to 250 Million') on conflict do nothing;

-- zi_department
-- 
INSERT INTO public.zi_department (value) VALUES
	 ('Operations'),
	 ('Military And Protective Services'),
	 ('Information Technology'),
	 ('Sales'),
	 ('Real Estate'),
	 ('Legal'),
	 ('Engineering'),
	 ('Media And Communications'),
	 ('Executive'),
	 ('Government') on conflict do nothing;
INSERT INTO public.zi_department (value) VALUES
	 ('Finance'),
	 ('Product Management'),
	 ('Community And Social Services'),
	 ('Human Resources'),
	 ('Administrative'),
	 ('Health Services'),
	 ('Education'),
	 ('Marketing') on conflict do nothing;

-- zi_industry
-- 
INSERT INTO public.zi_industry (value) VALUES
	 ('Drapery And Upholstery Stores'),
	 ('Pleating And Stitching'),
	 ('Deep Sea Passenger Trans., Except Ferry'),
	 ('Adhesives & Sealants'),
	 ('Bakery Products'),
	 ('Relays And Industrial Controls'),
	 ('Sporting And Recreational Camps'),
	 ('Wholesale-Motor Vehicle Supplies & New Parts'),
	 ('Excavation Work'),
	 ('Miscellaneous Plastics Products') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Civic And Social Associations'),
	 ('Services-Social Services'),
	 ('Knitting Mills'),
	 ('Services-Child Day Care Services'),
	 ('Wet Corn Milling'),
	 ('Drawing & Insulating Of Nonferrous Wire'),
	 ('Glass Containers'),
	 ('Hardware, N.E.C.'),
	 ('Retail-Department Stores'),
	 ('Personal Leather Goods, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Machine Tools, Metal Cutting Types'),
	 ('Optical Goods Stores'),
	 ('Wholesale-Electronic Parts & Equipment, Nec'),
	 ('Clay Refractories'),
	 ('Commercial Art And Graphic Design'),
	 ('Wood Tv And Radio Cabinets'),
	 ('Floor Covering Stores'),
	 ('Footwear, (No Rubber)'),
	 ('Pottery Products, N.E.C.'),
	 ('Instruments And Related Products') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Terminal Maintenance Facilities For Motor Freight Transport'),
	 ('Drinking Places'),
	 ('Telegraph & Other Message Communications'),
	 ('Malt Beverages'),
	 ('Steel Investment Foundries'),
	 ('Book Stores'),
	 ('Local And Suburban Transit'),
	 ('Industrial Trucks, Tractors, Trailors & Stackers'),
	 ('Drycleaning Plants, Except Rug'),
	 ('Perfumes, Cosmetics & Other Toilet Preparations') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Misc. Homefurnishings Stores'),
	 ('Commercial Laundry Equipment'),
	 ('Services-Health Services'),
	 ('Marinas'),
	 ('Automotive Stampings'),
	 ('Services-Educational Services'),
	 ('Pipelines, Except Natural Gas'),
	 ('Telephone Communications (No Radiotelephone)'),
	 ('Amusement And Recreation, N.E.C.'),
	 ('Men''S And Boys'' Shirts') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Wholesale-Hardware & Plumbing & Heating Equipment & Supplies'),
	 ('Boat Building And Repairing'),
	 ('Mobile Homes'),
	 ('Painting And Paper Hanging'),
	 ('Electrical Equipment & Supplies, N.E.C.'),
	 ('Metalworkg Machinery & Equipment'),
	 ('Services-Amusement & Recreation Services'),
	 ('Specialty Cleaning, Polishing And Sanitation Preparations'),
	 ('Petroleum And Coal Products, N.E.C.'),
	 ('Papers & Allied Products') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Agricultural Prod-Livestock & Animal Specialties'),
	 ('Dolls & Stuffed Toys'),
	 ('Laundry And Garment Services, N.E.C.'),
	 ('Miscellaneous Furniture & Fixtures'),
	 ('Housefurnishings, N.E.C.'),
	 ('Finishing Plants, Cotton'),
	 ('Retail-Grocery Stores'),
	 ('Lime'),
	 ('Unclassified Establishments'),
	 ('Insurance Carriers') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Passenger Transport Arrangement, N.E.C.'),
	 ('Tour Operators'),
	 ('Trusts, N.E.C.'),
	 ('Wholesale-Miscellaneous Nondurable Goods'),
	 ('Jewelry, Precious Metal'),
	 ('Girls'' And Children''S Outerwear, N.E.C.'),
	 ('Converted Paper Products, N.E.C.'),
	 ('Rooming And Boarding Houses'),
	 ('Commercial Banks'),
	 ('Hardwood Veneer And Plywood') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Industrial Supplies'),
	 ('Museums, Botanical, Zoological Gardens'),
	 ('Colleges And Universities'),
	 ('Trucking & Courier Services (No Air)'),
	 ('Hotels & Motels'),
	 ('General Bldg Contractors - Residential Bldgs'),
	 ('Flour And Other Grain Mill Products'),
	 ('Services-Membership Organizations'),
	 ('Livestock'),
	 ('Services-Commercial Physical & Biological Research') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Retail-Hobby, Toy & Game Shops'),
	 ('Synthetic Rubber'),
	 ('Tire Cord And Fabrics'),
	 ('Chewing Gum'),
	 ('Bookbinding And Related Work'),
	 ('Services-Computer Programming Services'),
	 ('Fluid Power Cylinders & Actuators'),
	 ('Ferries'),
	 ('Crushed And Broken Stone'),
	 ('Transportation Equipment') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Services-Motion Picture & Video Tape Distribution'),
	 ('Electron Tubes'),
	 ('Paper Coated And Laminated, N.E.C.'),
	 ('Water Transportation Of Freight, N.E.C.'),
	 ('Plastics, Foil & Coated Paper Bags'),
	 ('Secondary Nonferrous Metals'),
	 ('Carburetors, Pistons, Rings, Valves'),
	 ('Crop Services'),
	 ('Physical Fitness Facilities'),
	 ('Industrial Inorganic Chemicals, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Sheet Metal Work'),
	 ('Cutlery'),
	 ('Prepared Fresh Or Frozen Fish & Seafoods'),
	 ('Costume Jewelry'),
	 ('Concrete Products, Except Block & Brick'),
	 ('Books'),
	 ('Internal Combustion Engines, N.E.C.'),
	 ('Electrical Repair Shops'),
	 ('Operators Of Nonresidential Buildings'),
	 ('Services-Equipment Rental & Leasing, Nec') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Noncurrent-Carrying Wiring Devices'),
	 ('Saw Blades And Handsaws'),
	 ('Offices & Clinics Of Medical Doctors'),
	 ('Service Establishment Equipment'),
	 ('Furniture And Fixtures'),
	 ('Lead Pencils And Art Goods'),
	 ('Electronic Capacitors'),
	 ('Water Supply'),
	 ('Heavy Construction, Except Highway'),
	 ('Phonograph Records & Prerecorded Audio Tapes & Disks') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Ser Administrative And Auxiliary'),
	 ('Toys And Hobby Goods And Supplies'),
	 ('Sausages & Other Prepared Meat Products'),
	 ('Operators Of Apartment Buildings'),
	 ('Mechanical Rubber Goods'),
	 ('Drilling Oil & Gas Wells'),
	 ('Refrigeration Equipment And Supplies'),
	 ('Natural Gas Liquids'),
	 ('Stationery Products'),
	 ('Instruments For Meas & Testing Of Electricity & Elec Signals') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Automotive Transmission Repair Shops'),
	 ('Computer & Office Equipment'),
	 ('PRIMARY_INDUSTRY'),
	 ('Drugs'),
	 ('Wholesale-Petroleum Bulk Stations & Terminals'),
	 ('Coal And Other Minerals And Ores'),
	 ('Masonry, Stonework, And Plastering'),
	 ('Communications Equipment'),
	 ('Steel Works, Blast Furnaces & Rolling Mills (Coke Ovens)'),
	 ('Coin-Operated Laundries And Cleaning') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Personnel Supply Services'),
	 ('Wire Springs'),
	 ('Logging'),
	 ('Aircraft Engines & Engine Parts'),
	 ('Depository Institutions'),
	 ('Services-Allied To Motion Picture Distribution'),
	 ('Services-Help Supply Services'),
	 ('Metal Foil And Leaf'),
	 ('Fabricated Metal Products'),
	 ('Mining & Quarrying Of Nonmetallic Minerals (No Fuels)') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Motion Picture Distribution & Services'),
	 ('Combination Utility Services'),
	 ('Reconstituted Wood Products'),
	 ('Real Estate Agents & Managers (For Others)'),
	 ('Jewelers'' Materials & Lapidary Work'),
	 ('Camera & Photographic Supply Stores'),
	 ('Services-Services, Nec'),
	 ('Retail-Apparel & Accessory Stores'),
	 ('Watches, Clocks, Clockwork Operated Devices/Parts'),
	 ('Hardwood Dimension & Flooring Mills') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Services-Computer Rental & Leasing'),
	 ('Corrugated And Solid Fiber Boxes'),
	 ('Hard Surface Floor Coverings, N.E.C.'),
	 ('Services-Computer Programming, Data Processing, Etc.'),
	 ('Hand And Edge Tools, N.E.C.'),
	 ('Services-Membership Sports & Recreation Clubs'),
	 ('Women''S And Misses'' Suits And Coats'),
	 ('Ship Building And Repairing'),
	 ('Services-Racing, Including Track Operation'),
	 ('Special Product Sawmills, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Clay, Ceramic, & Refractory Minerals'),
	 ('Bread, Cake, And Related Products'),
	 ('Title Insurance'),
	 ('Printing Ink'),
	 ('Combination Utilities, N.E.C.'),
	 ('Miscellaneous Personal Services, N.E.C.'),
	 ('Curtains And Draperies'),
	 ('Plumbing Fixture Fittings And Trim'),
	 ('Silver Ores'),
	 ('Girls'' & Children''S Dresses, Blouses') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Miscellaneous Metal Ores'),
	 ('Top & Body Repair & Paint Shops'),
	 ('Services-Telephone Interconnect Systems'),
	 ('Nonwoven Fabrics'),
	 ('Brick And Structural Clay Tile'),
	 ('Travel Trailers And Campers'),
	 ('Burial Caskets'),
	 ('Retail-Misc General Merchandise Stores'),
	 ('Credit Unions'),
	 ('Power-Driven Handtools') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Setup Paperboard Boxes'),
	 ('Direct Selling Establishments'),
	 ('Food Products Machinery'),
	 ('Investment Advice'),
	 ('Service Industries For The Printing Trade'),
	 ('Wood Office Furniture'),
	 ('Miscellaneous Metal Work'),
	 ('Motor Homes'),
	 ('Real Estate'),
	 ('Manufactured Ice') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Holding And Other Investment Offices'),
	 ('Services-Offices & Clinics Of Doctors Of Medicine'),
	 ('Sawmills & Planting Mills, General'),
	 ('Water Transportation'),
	 ('Electronic Components & Accessories'),
	 ('Fabricated Metal Products, N.E.C.'),
	 ('Electronic Coils, Transformers & Other Inductors'),
	 ('Industrial Instruments For Measurement, Display, And Control'),
	 ('Search, Detection, Navagation, Guidance, Aeronautical Sys'),
	 ('Textile Bags') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Plastic Material, Synth Resin/Rubber, Cellulos (No Glass)'),
	 ('Heating Equipment, Except Electric & Warm Air Furnaces'),
	 ('Electronic Connectors'),
	 ('Local Bus Charter Service'),
	 ('Bituminous Coal Underground'),
	 ('Footwear Cut Stock'),
	 ('Wholesale-Computers & Peripheral Equipment & Software'),
	 ('Wholesale-Lumber, Plywood, Millwork & Wood Panels'),
	 ('Utility Trailer Rental'),
	 ('Machine Tools, Metal Forming Types') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Ordnance & Accessories, (No Vehicles/Guided Missiles)'),
	 ('Gift, Novelty, And Souvenir Shops'),
	 ('Men''S And Boys'' Neckwear'),
	 ('Hospital & Medical Service Plans'),
	 ('Oil & Gas Field Services, Nec'),
	 ('Aircraft Parts & Auxiliary Equipment, Nec'),
	 ('Mattresses And Bedsprings'),
	 ('Industrial Patterns'),
	 ('Telephone & Telegraph Apparatus'),
	 ('Marine Cargo Handling') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Partitions And Fixtures, Except Wood'),
	 ('Power Laundries, Family & Commercial'),
	 ('Miscellaneous Primary Metal Products'),
	 ('Structural Clay Products, N.E.C.'),
	 ('Rubber & Plastics Footwear'),
	 ('Broadwoven Fabric Mills, Cotton'),
	 ('Services-Automotive Repair, Services & Parking'),
	 ('Printing And Publishing'),
	 ('Forestry'),
	 ('Household Appliances') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Ordnance And Accessories, N.E.C.'),
	 ('Dry, Condensed, Evaporated Products'),
	 ('Knit Underwear Mills'),
	 ('Services-General Medical & Surgical Hospitals, Nec'),
	 ('Services-Employment Agencies'),
	 ('Stationery And Office Supplies'),
	 ('Industrial Process Furnaces & Ovens'),
	 ('Laboratory Analytical Instruments'),
	 ('Primary Smelting & Refining Of Nonferrous Metals'),
	 ('Scales And Balances, Exc. Laboratory') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Frozen Bakery Products, Except Bread'),
	 ('Prefabricated Wood Bldgs & Components'),
	 ('Miscellaneous Publishing'),
	 ('Crushed And Broken Limestone'),
	 ('Noncommercial Research Organizations'),
	 ('Gas Production And Distribution'),
	 ('Services-Management Services'),
	 ('Knit Outerwear Mills'),
	 ('Food Preparations, N.E.C.'),
	 ('Carpentry Work') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Aluminum Sheet, Plate, And Foil'),
	 ('Weft Knit Fabric Mills'),
	 ('Canned And Cured Fish And Seafoods'),
	 ('Services-Home Health Care Services'),
	 ('Tires & Inner Tubes'),
	 ('Architectural Metal Work'),
	 ('Dental Equipment & Supplies'),
	 ('Stone, Clay, And Glass Products'),
	 ('Wholesale-Industrial Machinery & Equipment'),
	 ('Wood Products, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Copper Ores'),
	 ('Paper Mills'),
	 ('Women''S, Junior''S, & Misses'' Dresses'),
	 ('Theatrical Producers And Services'),
	 ('Farm Management Services'),
	 ('Paint, Glass, And Wallpaper Stores'),
	 ('Merchandising Machine Operators'),
	 ('Switchgear & Switchboard Apparatus'),
	 ('Services-Motion Picture Theaters'),
	 ('Landscape And Horticultural Services') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Computer Related Services, N.E.C.'),
	 ('Canvas And Related Products'),
	 ('Transportation By Air'),
	 ('Services-Direct Mail Advertising Services'),
	 ('Canned Specialties'),
	 ('Plastics Materials & Basic Shapes'),
	 ('Services-Business Services, Nec'),
	 ('Masonry And Other Stonework'),
	 ('Travel Agencies'),
	 ('Commercial Printing, Gravure') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Metal Heat Treating'),
	 ('Miscellaneous Food Preparations & Kindred Products'),
	 ('Foreign Governments'),
	 ('Offices And Clinics Of Chiropractors'),
	 ('Services-Engineering Services'),
	 ('Household Refrigerators And Freezers'),
	 ('Fluid Milk'),
	 ('Tobacco And Tobacco Products'),
	 ('Services-Auto Rental & Leasing (No Drivers)'),
	 ('International Affairs') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Carbon And Graphite Products'),
	 ('Paints, Varnishes, And Supplies'),
	 ('Wood Containers, N.E.C.'),
	 ('Robes And Dressing Gowns'),
	 ('Retail-Computer & Computer Software Stores'),
	 ('Service Industry Machinery, N.E.C.'),
	 ('Miscellaneous Retail Stores, N.E.C.'),
	 ('Funeral Service And Crematories'),
	 ('Rice Milling'),
	 ('Services-Legal Services') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Elevators And Moving Stairways'),
	 ('Industrial Organic Chemicals, N.E.C.'),
	 ('Industrial Sand'),
	 ('Crowns And Closures'),
	 ('Musical Instruments'),
	 ('Folding Paperboard Boxes'),
	 ('Concrete, Gypsum & Plaster Products'),
	 ('Cable & Other Pay Television Services'),
	 ('Nonferrous Foundries, N.E.C.'),
	 ('Scrap And Waste Materials') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Thread Mills'),
	 ('Totalizing Fluid Meters & Counting Devices'),
	 ('Credit Reporting Services'),
	 ('Metal Forgings & Stampings'),
	 ('Textile Goods, N.E.C.'),
	 ('Carbon Paper And Inked Ribbons'),
	 ('Meat Packing Plants'),
	 ('Pipelines, N.E.C.'),
	 ('Office Furniture (No Wood)'),
	 ('General Contractors & Operative Builders') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Commercial Printing, N.E.C.'),
	 ('Lumber & Wood Products (No Furniture)'),
	 ('Insurance Agents, Brokers, & Service'),
	 ('Liquor Stores'),
	 ('Laboratory Apparatus & Furniture'),
	 ('Real Estate Investment Trusts'),
	 ('Copper Foundries'),
	 ('Wood Preserving'),
	 ('Telephone Communication'),
	 ('Motor Vehicle Parts, Used') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Cigars'),
	 ('Retail-Miscellaneous Retail'),
	 ('Fish And Seafoods'),
	 ('Retail-Lumber & Other Building Materials Dealers'),
	 ('Semiconductors & Related Devices'),
	 ('Metal Stampings, N.E.C.'),
	 ('Kaolin And Ball Clay'),
	 ('Steel Foundries, N.E.C.'),
	 ('Truck Rental And Leasing, No Drivers'),
	 ('Motion Picture Theaters, Ex Drive-In') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Public Golf Courses'),
	 ('Soaps And Other Detergents'),
	 ('Garment Pressing & Cleaners'' Agents'),
	 ('Cut Stone & Stone Products'),
	 ('Wholesale-Beer, Wine & Distilled Alcoholic Beverages'),
	 ('Homefurnishings'),
	 ('Nondurable Goods, N.E.C.'),
	 ('Phosphate Rock'),
	 ('Educational, Religious, Etc. Trusts'),
	 ('Conveyors And Conveying Equipment') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Printed Circuit Boards'),
	 ('Paints And Allied Products'),
	 ('Motion Picture Production & Services'),
	 ('Books, Periodicals, & Newspapers'),
	 ('Metal Coating And Allied Services'),
	 ('Prepared Flour Mixes And Doughs'),
	 ('Vitreous Plumbing Fixtures'),
	 ('Lead And Zinc Ores'),
	 ('Services-Computer Processing & Data Preparation'),
	 ('Ball & Roller Bearings') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Public Bldg & Related Furniture'),
	 ('Apparel Belts'),
	 ('Uranium-Radium-Vanadium Ores 1099 Metal Ores, N.E.C.'),
	 ('Bottled & Canned Soft Drinks & Carbonated Waters'),
	 ('Air Transportation, Nonscheduled'),
	 ('Savings Institution, Federally Chartered'),
	 ('X-Ray Apparatus & Tubes & Related Irradiation Apparatus'),
	 ('Services-Advertising'),
	 ('Highway And Street Construction'),
	 ('Building Maintenance Services, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Furniture'),
	 ('Farm Machinery & Equipment'),
	 ('Sanitary Paper Products'),
	 ('Metal Doors, Sash, Frames, Moldings & Trim'),
	 ('Auto Exhaust System Repair Shops'),
	 ('Steel Springs, Except Wire'),
	 ('Armature Rewinding Shops'),
	 ('Mining Machinery & Equip (No Oil & Gas Field Mach & Equip)'),
	 ('Drive-In Motion Picture Theaters'),
	 ('Fasteners, Buttons, Needles, & Pins') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Electromedical & Electrotherapeutic Apparatus'),
	 ('Electrometallurgical Products'),
	 ('Explosives'),
	 ('Real Estate Dealers (For Their Own Account)'),
	 ('Glass And Glazing Work'),
	 ('Frozen Specialties, N.E.C.'),
	 ('Agricultural Chemicals, N.E.C.'),
	 ('General Industrial Machinery & Equipment, Nec'),
	 ('Household Laundry Equipment'),
	 ('Fabricated Structural Metal') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Offices And Clinics Of Podiatrists'),
	 ('Primary Metal Products, N.E.C.'),
	 ('Vegetable Oil Mills, N.E.C.'),
	 ('Nonmetallic Mineral Products, N.E.C.'),
	 ('Electrical Repair Shops, N.E.C.'),
	 ('Heavy Construction Equipment Rental'),
	 ('Oil Royalty Traders'),
	 ('Confectionery'),
	 ('Communications Equipment, Nec'),
	 ('Gold Ores') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Wholesale-Electrical Appliances, Tv & Radio Sets'),
	 ('Aluminum Die-Castings'),
	 ('Distilled And Blended Liquors'),
	 ('Aluminum Rolling And Drawing, N.E.C.'),
	 ('Coated Fabrics, Not Rubberized'),
	 ('Laminated Plastics Plate & Sheet'),
	 ('Retail-Jewelry Stores'),
	 ('Railroad Equipment'),
	 ('Plastics Products, Nec'),
	 ('Brooms And Brushes') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Investors, Nec'),
	 ('Welding Apparatus'),
	 ('Insurance Carriers, Nec'),
	 ('Wholesale-Durable Goods, Nec'),
	 ('Natural Gas Transmisison & Distribution'),
	 ('Air-Cond & Warm Air Heatg Equip & Comm & Indl Refrig Equip'),
	 ('Transportation Services'),
	 ('Household Cooking Equipment'),
	 ('Piece Goods & Notions'),
	 ('Secondary Smelting & Refining Of Nonferrous Metals') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Wholesale-Electrical Apparatus & Equipment, Wiring Supplies'),
	 ('Wood Kitchen Cabinets'),
	 ('Wholesale-Durable Goods'),
	 ('Fire, Marine & Casualty Insurance'),
	 ('Chemical And Fertilizer Mining, N.E.C.'),
	 ('Operative Builders'),
	 ('Cemetery Subdividers And Developers'),
	 ('Creamery Butter'),
	 ('Space Propulsion Units And Parts'),
	 ('Meats And Meat Products') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Household Furniture, N.E.C.'),
	 ('Nonferrous Die-Casting Exc. Aluminum'),
	 ('Farm And Garden Machinery'),
	 ('Automotive Glass Replacement Shops'),
	 ('Wholesale-Construction & Mining (No Petro) Machinery & Equip'),
	 ('Men''S Footwear, Except Athletic'),
	 ('Trailer Parks And Campsites'),
	 ('Chemicals & Allied Products, N.E.C.'),
	 ('Accident & Health Insurance'),
	 ('Motor Vehicles & Passenger Car Bodies') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Pressed And Blown Glass, N.E.C.'),
	 ('Farm Labor And Management Services'),
	 ('National Commercial Banks'),
	 ('Dairy Products, Exc. Dried Or Canned'),
	 ('Nitrogenous Fertilizers'),
	 ('Transportation Equipment, N.E.C.'),
	 ('Wholesale-Professional & Commercial Equipment & Supplies'),
	 ('Candy & Other Confectionery Products'),
	 ('Commercial Printing, Lithographic'),
	 ('Footwear, Except Rubber, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Small Arms'),
	 ('Women''S Clothing Stores'),
	 ('Refuse Systems'),
	 ('Surety Insurance'),
	 ('New And Used Car Dealers'),
	 ('Wholesale-Hardware'),
	 ('Railroad Switching & Terminal Establishments'),
	 ('Services-Testing Laboratories'),
	 ('Salted And Roasted Nuts And Seeds'),
	 ('Cane Sugar Refining') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Rubber And Misc. Plastics Products'),
	 ('Tobacco Stores And Stands'),
	 ('Storage Batteries'),
	 ('Copper Rolling And Drawing'),
	 ('Steel Wire And Related Products'),
	 ('Tires And Tubes'),
	 ('Ophthalmic Goods'),
	 ('Installing Building Equipment, N.E.C.'),
	 ('Commercial Banks, Nec'),
	 ('Wholesale-Motor Vehicles & Motor Vehicle Parts & Supplies') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Prepared Feeds, N.E.C.'),
	 ('Offices Of Osteopathic Physicians'),
	 ('Furniture And Homefurnishings Stores'),
	 ('Small Arms Ammunition'),
	 ('Radio & Tv Broadcasting & Communications Equipment'),
	 ('Hotels, Rooming Houses, Camps & Other Lodging Places'),
	 ('Farm Supplies'),
	 ('Sanitary Food Containers'),
	 ('Household Appliances, N.E.C.'),
	 ('Packaging Machinery') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Asbestos Products'),
	 ('Subdividers And Developers'),
	 ('Truck & Bus Bodies'),
	 ('Canned, Frozen & Preservd Fruit, Veg & Food Specialties'),
	 ('Services-Hospitals'),
	 ('Ammunition, Exc. For Small Arms, N.E.C.'),
	 ('Aircraft'),
	 ('Services-Advertising Agencies'),
	 ('Poultry And Poultry Products'),
	 ('Electric Housewares & Fans') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Wholesale-Jewelry, Watches, Precious Stones & Metals'),
	 ('Office Machines, Nec'),
	 ('Services-Motion Picture & Video Tape Production'),
	 ('Services-Management Consulting Services'),
	 ('Fluid Power Pumps And Motors'),
	 ('Disinfecting & Pest Control Services'),
	 ('Miscellaneous Business Credit Institution'),
	 ('Typesetting'),
	 ('Retail-Women''S Clothing Stores'),
	 ('Metal Shipping Barrels, Drums, Kegs & Pails') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Electrical Industrial Apparatus'),
	 ('Measuring & Controlling Devices, Nec'),
	 ('Construction Machinery & Equip'),
	 ('Knitting Mills, N.E.C.'),
	 ('Primary Nonferrous Metals, N.E.C.'),
	 ('Security Brokers, Dealers & Flotation Companies'),
	 ('Unsupported Plastics Profile Shapes'),
	 ('Cottonseed Oil Mills'),
	 ('Mineral Wool'),
	 ('News Syndicates') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Plastics Bottles'),
	 ('Organic Fibers, Noncellulosic'),
	 ('Carpentry And Floor Work'),
	 ('Motor Vehicle Parts & Accessories'),
	 ('Electric Services'),
	 ('Silverware And Plated Ware'),
	 ('Dental Laboratories'),
	 ('Pickles, Sauces, And Salad Dressings'),
	 ('Luggage And Leather Goods Stores'),
	 ('Water, Sewer, Pipeline, Comm & Power Line Construction') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Brick, Stone, & Related Materials'),
	 ('Automotive Services, N.E.C.'),
	 ('Florists'),
	 ('Cut Stone And Stone Products'),
	 ('Land Subdividers & Developers (No Cemeteries)'),
	 ('Special Trade Contractors, N.E.C.'),
	 ('Food And Kindred Products'),
	 ('Cold Finishing Of Steel Shapes'),
	 ('Electronic Components, Nec'),
	 ('Leather And Sheep-Lined Clothing') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Potash, Soda, And Borate Minerals'),
	 ('Computer Peripheral Equipment, Nec'),
	 ('Women''S And Children''S Underwear'),
	 ('Upholstered Household Furniture'),
	 ('Bras, Girdles, And Allied Garments'),
	 ('Prefabricated Metal Buildings & Components'),
	 ('Tanks And Tank Components'),
	 ('Nondepository Institutions'),
	 ('Tires And Inner Tubes'),
	 ('Wholesale-Farm Product Raw Materials') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Plastics Plumbing Fixtures'),
	 ('Photographic Studios, Portrait'),
	 ('Women''S Hosiery, Except Socks'),
	 ('Footwear'),
	 ('Calculating & Accounting Machines (No Electronic Computers)'),
	 ('Services-Medical Laboratories'),
	 ('Computer Communications Equipment'),
	 ('Automotive And Apparel Trimmings'),
	 ('Nonferrous Foundries (Castings)'),
	 ('Electrical Work') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Trucking (No Local)'),
	 ('General Warehousing And Storage'),
	 ('Nonferrous Rolling And Drawing, N.E.C.'),
	 ('Manufacturing Industries, N.E.C.'),
	 ('Oil And Gas Extraction'),
	 ('Phosphatic Fertilizers'),
	 ('House Slippers'),
	 ('Partitions, Shelvg, Lockers, & Office & Store Fixtures'),
	 ('Sports Clubs, Managers, & Promoters'),
	 ('Finance Services') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Pulp Mills'),
	 ('Retail-Food Stores'),
	 ('Electric Lamps'),
	 ('Women''S & Misses'' Blouses & Shirts'),
	 ('Commercial Equipment, N.E.C.'),
	 ('Deep Sea Foreign Transportation Of Freight'),
	 ('Sporting Goods And Bicycle Shops'),
	 ('Wholesale-Groceries & Related Products'),
	 ('Services-Engineering, Accounting, Research, Management'),
	 ('Pens And Mechanical Pencils') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Passenger Car Rental'),
	 ('Retail-Auto Dealers & Gasoline Stations'),
	 ('Potato Chips And Similar Snacks'),
	 ('Retail-Family Clothing Stores'),
	 ('Water Passenger Transportation, N.E.C.'),
	 ('Secretarial & Court Reporting'),
	 ('Political Organizations'),
	 ('Marking Devices'),
	 ('Business Consulting, N.E.C.'),
	 ('Ferroalloy Ores, Except Vanadium') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Men''S And Boys'' Work Clothing'),
	 ('Surgical & Medical Instruments & Apparatus'),
	 ('Agricultural Services'),
	 ('Clay And Related Minerals, N.E.C.'),
	 ('Nonclay Refractories'),
	 ('Ready-Mixed Concrete'),
	 ('Local Passenger Transportation, N.E.C.'),
	 ('Roofing, Siding, & Sheet Metal Work'),
	 ('In Vitro & In Vivo Diagnostic Substances'),
	 ('Men''S And Boys'' Clothing, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Finishing Plants, N.E.C.'),
	 ('Insurance Agents, Brokers & Service'),
	 ('Elementary And Secondary Schools'),
	 ('Orthopedic, Prosthetic & Surgical Appliances & Supplies'),
	 ('Gaskets, Packing And Sealing Devices'),
	 ('Air And Gas Compressors'),
	 ('Pharmaceutical Preparations'),
	 ('Sand And Gravel'),
	 ('Lubricating Oils And Greases'),
	 ('Speed Changers, Drives, And Gears') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Primary Copper'),
	 ('Signs And Advertising Specialities'),
	 ('Heating Equip, Except Elec & Warm Air, & Plumbing Fixtures'),
	 ('Photocopying & Duplicating Services'),
	 ('Glass & Glassware, Pressed Or Blown'),
	 ('Platemaking Services'),
	 ('Plating And Polishing'),
	 ('Metal Mining'),
	 ('Envelopes'),
	 ('Rubber & Plastics Hose & Belting') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Retail-Auto & Home Supply Stores'),
	 ('Industrial Machinery And Equipment'),
	 ('Wholesale-Metals Service Centers & Offices'),
	 ('Industrial Launderers'),
	 ('Fabricated Textile Products, N.E.C.'),
	 ('Commercial Photography'),
	 ('Accounting, Auditing, & Bookkeeping'),
	 ('Agricultural Chemicals'),
	 ('Construction Materials, N.E.C.'),
	 ('Power Transmission Equipment, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Lace & Warp Knit Fabric Mills'),
	 ('Musical Instrument Stores'),
	 ('Bags: Uncoated Paper & Multiwall'),
	 ('Linen Supply'),
	 ('Oil & Gas Field Exploration Services'),
	 ('Fire, Marine, And Casualty Insurance'),
	 ('Photographic Equipment And Supplies'),
	 ('Metalworking Machinery, N.E.C.'),
	 ('Public Relations Services'),
	 ('Waterproof Outerwear') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Women''S And Children''S Clothing'),
	 ('Services-Computer Integrated Systems Design'),
	 ('Water Well Drilling'),
	 ('Wholesale-Petroleum & Petroleum Products (No Bulk Stations)'),
	 ('Metal Sanitary Ware'),
	 ('Fertilizers, Mixing Only'),
	 ('Towing And Tugboat Service'),
	 ('Wood Pallets And Skids'),
	 ('Oil & Gas Field Machinery & Equipment'),
	 ('Printing Trades Machinery & Equipment') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Real Estate Operators (No Developers) & Lessors'),
	 ('Fiber Cans, Drums & Similar Products'),
	 ('Cheese, Natural And Processed'),
	 ('Drapery Hardware & Blinds & Shades'),
	 ('Iron And Steel Forgings'),
	 ('Surface Active Agents'),
	 ('Schools & Educational Services, N.E.C.'),
	 ('Services-Photofinishing Laboratories'),
	 ('Fabricated Rubber Products, N.E.C.'),
	 ('Special Warehousing And Storage, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Fuel Oil Dealers'),
	 ('Nonmetallic Minerals Services'),
	 ('Biological Products, (No Disgnostic Substances)'),
	 ('Pottery & Related Products'),
	 ('Macaroni And Spaghetti'),
	 ('Miscellaneous Manufacturing Industries'),
	 ('Fuel Dealers, N.E.C.'),
	 ('Professional Equipment, N.E.C.'),
	 ('Services-Skilled Nursing Care Facilities'),
	 ('Hoists, Cranes, And Monorails') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Carwashes'),
	 ('Concrete Block And Brick'),
	 ('Savings Institutions, Not Federally Chartered'),
	 ('Business Services'),
	 ('Natural Gas Distribution'),
	 ('Misc. Fabricated Wire Products'),
	 ('Measuring And Dispensing Pumps'),
	 ('Auto Controls For Regulating Residential & Comml Environments'),
	 ('Flat Glass'),
	 ('Engines & Turbines') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Paints, Varnishes, Lacquers, Enamels & Allied Prods'),
	 ('Wholesale-Drugs, Proprietaries & Druggists'' Sundries'),
	 ('Farm-Product Raw Materials, N.E.C.'),
	 ('Guided Missiles And Space Vehicles'),
	 ('Radio Broadcasting Stations'),
	 ('Refrigerated Warehousing And Storage'),
	 ('General Merchandise Stores'),
	 ('Liquefied Petroleum Gas Dealers'),
	 ('Raw Cane Sugar'),
	 ('Electronic Resistors') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Sanitary Services'),
	 ('Motorcycles, Bicycles & Parts'),
	 ('Local & Suburban Transit & Interurban Hwy Passenger Trans'),
	 ('Services-Mailing, Reproduction, Commercial Art & Photography'),
	 ('Commercial Lighting Fixtures'),
	 ('Computer Storage Devices'),
	 ('Functions Related To Depository Banking, Nec'),
	 ('Plumbing, Heating, Air-Conditioning'),
	 ('Services-Personal Services'),
	 ('Optical Instruments & Lenses') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Metal Mining Services'),
	 ('Semivitreous Table & Kitchenware'),
	 ('Outdoor Advertising Services'),
	 ('Security & Commodity Brokers, Dealers, Exchanges & Services'),
	 ('Malt'),
	 ('Local And Suburban Transportation'),
	 ('Telegraph & Other Communications'),
	 ('Investment Offices'),
	 ('Patent Owners & Lessors'),
	 ('Primary Batteries, Dry And Wet') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Commercial Nonphysical Research'),
	 ('News Dealers And Newsstands'),
	 ('Dairy Products'),
	 ('Bolts, Nuts, Screws, Rivets & Washers'),
	 ('Power, Distribution & Specialty Transformers'),
	 ('Coin-Operated Amusement Devices'),
	 ('Warm Air Heating & Air-Conditioning'),
	 ('Arrangement Of Transportation Of Freight & Cargo'),
	 ('Screw Machine Products'),
	 ('Hosiery, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Amusement Parks'),
	 ('Aircraft & Parts'),
	 ('Cordage And Twine'),
	 ('Repair Services, N.E.C.'),
	 ('Porcelain Electrical Supplies'),
	 ('Textile Machinery'),
	 ('Current-Carrying Wiring Devices'),
	 ('Communication'),
	 ('Broadwoven Fabric Mills, Manmade'),
	 ('Fresh Fruits And Vegetables') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Television Broadcasting Stations'),
	 ('Men''S & Boys'' Underwear + Nightwear'),
	 ('Truck Trailers'),
	 ('Fabricated Pipe And Fittings'),
	 ('Periodicals: Publishing Or Publishing & Printing'),
	 ('Gas & Other Services Combined'),
	 ('Offices Of Health Practitioners, N.E.C.'),
	 ('Crushed And Broken Granite'),
	 ('Industrial Gases'),
	 ('Groceries And Related Products, N.E.C.') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Carpet And Upholstery Cleaning'),
	 ('State Commercial Banks'),
	 ('Retail-Record & Prerecorded Tape Stores'),
	 ('Refrigeration Service And Repair'),
	 ('Turbines And Turbine Generator Sets'),
	 ('Floor Laying And Floor Work, N.E.C.'),
	 ('Engineering & Architectural Services'),
	 ('Bituminous Coal & Lignite Mining'),
	 ('Photographic Equipment & Supplies'),
	 ('Roasted Coffee') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Chewing And Smoking Tobacco'),
	 ('Services-Video Tape Rental'),
	 ('Paperboard Mills'),
	 ('Vitreous China Table & Kitchenware'),
	 ('Lessors Of Real Property, Nec'),
	 ('Carpets & Rugs'),
	 ('Packaged Frozen Foods'),
	 ('Rolling Mill Machinery'),
	 ('Cigarettes'),
	 ('Tax Return Preparation Services') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Residential Lighting Fixtures'),
	 ('Gum And Wood Chemicals'),
	 ('Crude Petroleum & Natural Gas'),
	 ('Sewing, Needlework, And Piece Goods'),
	 ('Books: Publishing Or Publishing & Printing'),
	 ('Chemical Preparations, N.E.C.'),
	 ('Coal Mining'),
	 ('Nonferrous Forgings'),
	 ('Refrigeration & Service Industry Machinery'),
	 ('Die-Cut Paper And Board') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Women''S Handbags And Purses'),
	 ('Computer Terminals'),
	 ('Unsupported Plastics Film & Sheet'),
	 ('Information Retrieval Services'),
	 ('Automobile Parking'),
	 ('Wholesale-Medical, Dental & Hospital Equipment & Supplies'),
	 ('Radio And Television Repair'),
	 ('Aluminum Foundries'),
	 ('Household Audio & Video Equipment'),
	 ('Gray And Ductile Iron Foundries') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Bus Charter Service, Except Local'),
	 ('Terrazzo, Tile, Marble, Mosaic Work'),
	 ('Household Audio And Video Equipment'),
	 ('Household Furniture'),
	 ('Retail-Convenience Stores'),
	 ('Yarn Spinning Mills'),
	 ('Passenger Car Leasing'),
	 ('Animal And Marine Fats And Oils'),
	 ('Retail-Nonstore Retailers'),
	 ('Frozen Fruits And Vegetables') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Cookies & Crackers'),
	 ('Grain And Field Beans'),
	 ('Crude Petroleum And Natural Gas'),
	 ('Bituminous Coal & Lignite Surface Mining'),
	 ('Printing And Writing Paper'),
	 ('Medical Equipment Rental'),
	 ('Vehicular Lighting Equipment'),
	 ('Inorganic Pigments'),
	 ('Automotive Repair Shops, N.E.C.'),
	 ('Broadwoven Fabric Mills, Wool') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Gypsum Products'),
	 ('Ceramic Wall And Floor Tile'),
	 ('Plastics Foam Products'),
	 ('Magnetic & Optical Recording Media'),
	 ('Apparel And Accessories, N.E.C.'),
	 ('Transportation Equipment & Supplies'),
	 ('Canned, Fruits, Veg, Preserves, Jams & Jellies'),
	 ('Communications Services, Nec'),
	 ('Legal Services'),
	 ('Book Printing') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Farm Product Warehousing And Storage'),
	 ('Lawn & Garden Tractors & Home Lawn & Gardens Equip'),
	 ('Plastic Materials, Synth Resins & Nonvulcan Elastomers'),
	 ('Railroads, Line-Haul Operating'),
	 ('Special Dies, Tools, Jigs & Fixtures'),
	 ('Asphalt Paving Mixtures And Blocks'),
	 ('Wrecking And Demolition Work'),
	 ('Steel Pipe & Tubes'),
	 ('Aluminum Extruded Products'),
	 ('Steam & Air-Conditioning Supply') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Loan Brokers'),
	 ('Poultry Slaughtering And Processing'),
	 ('Cereal Breakfast Foods'),
	 ('Greeting Cards'),
	 ('Pumps & Pumping Equipment'),
	 ('Valves And Pipe Fittings, N.E.C.'),
	 ('Security Systems Services'),
	 ('Cyclic Crudes And Intermediates'),
	 ('Wines, Brandy, And Brandy Spirits'),
	 ('Services-Prepackaged Software') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Household Vacuum Cleaners'),
	 ('Nailed Wood Boxes And Shook'),
	 ('Electronic & Other Electrical Equipment (No Computer Equip)'),
	 ('Motors & Generators'),
	 ('Textile Mill Products'),
	 ('Sporting & Recreational Goods'),
	 ('Millwork'),
	 ('Apparel & Other Finishd Prods Of Fabrics & Similar Matl'),
	 ('Air Transportation, Scheduled'),
	 ('Industrial & Commercial Fans & Blowers & Air Purifing Equip') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Automatic Vending Machines'),
	 ('Paper Industries Machinery'),
	 ('Beer And Ale'),
	 ('Office Furniture'),
	 ('Transportation And Public Utilities'),
	 ('Radio, Tv, Publisher Representatives'),
	 ('Engine Electrical Equipment'),
	 ('Fabricated Plate Work (Boiler Shops)'),
	 ('Dog And Cat Food'),
	 ('Minerals, Ground Or Treated') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Services-Detective, Guard & Armored Car Services'),
	 ('Gasoline Service Stations'),
	 ('Plastics Pipe'),
	 ('Dehydrated Fruits, Vegetables, Soups'),
	 ('Adjustment & Collection Services'),
	 ('Entertainers & Entertainment Groups'),
	 ('Women''S Footwear, Except Athletic'),
	 ('Plastering, Drywall, And Insulation'),
	 ('Fishing, Hunting, And Trapping'),
	 ('Natural Gas Transmission') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Electric, Gas & Sanitary Services'),
	 ('Research And Testing Services'),
	 ('Construction Sand And Gravel'),
	 ('Management And Public Relations'),
	 ('Soil Preparation Services'),
	 ('Gold And Silver Ores'),
	 ('Industrial Machinery, N.E.C.'),
	 ('Retail-Catalog & Mail-Order Houses'),
	 ('Malleable Iron Foundries'),
	 ('Retail-Home Furniture, Furnishings & Equipment Stores') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Newspapers: Publishing Or Publishing & Printing'),
	 ('Throwing And Winding Mills'),
	 ('Beauty Shops'),
	 ('Advertising, N.E.C.'),
	 ('Primary Metal Industries'),
	 ('Rubber And Plastics Footwear'),
	 ('Services-Allied To Motion Picture Production'),
	 ('Cement, Hydraulic'),
	 ('Alkalies And Chlorine'),
	 ('Services-Consumer Credit Reporting, Collection Agencies') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Structural Wood Members, N.E.C.'),
	 ('Air Courier Services'),
	 ('Auto And Home Supply Stores'),
	 ('Radiotelephone Communications'),
	 ('Electronic Computers'),
	 ('Stationery Stores'),
	 ('Metal Household Furniture'),
	 ('Shoe Repair And Shoeshine Parlors'),
	 ('Agricultural Production-Crops'),
	 ('Wood Household Furniture, (No Upholstered)') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Retail-Mobile Home Dealers'),
	 ('Petroleum Refining'),
	 ('Surveying Services'),
	 ('Custom Compound Purchased Resins'),
	 ('Welding Repair'),
	 ('Sporting & Athletic Goods, Nec'),
	 ('Tire Retreading And Repair Shops'),
	 ('Animal Services, Except Veterinary'),
	 ('Soybean Oil Mills'),
	 ('Hats, Caps, And Millinery') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Computer Facilities Management'),
	 ('Retail-Variety Stores'),
	 ('Games, Toys & Children''S Vehicles (No Dolls & Bicycles)'),
	 ('Coal Mining Services'),
	 ('Men''S And Boys'' Clothing'),
	 ('Life Insurance'),
	 ('Trucking And Warehousing'),
	 ('Construction - Special Trade Contractors'),
	 ('Space Vehicle Equipment, N.E.C.'),
	 ('Electric & Other Services Combined') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Men''S And Boys'' Trousers And Slacks'),
	 ('Federal & Federally-Sponsored Credit Agencies'),
	 ('Commodity Contracts Brokers & Dealers'),
	 ('Petroleum And Coal Products'),
	 ('Services-Specialty Outpatient Facilities, Nec'),
	 ('Retail-Furniture Stores'),
	 ('Beet Sugar'),
	 ('Tobacco Stemming And Redrying'),
	 ('Woodworking Machinery'),
	 ('Architectural Services') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Medicinal Chemicals & Botanical Products'),
	 ('Mortgage Bankers & Loan Correspondents'),
	 ('Retail-Radio, Tv & Consumer Electronics Stores'),
	 ('Farm Labor Contractors'),
	 ('Commercial Printing'),
	 ('Offices And Clinics Of Optometrists'),
	 ('Edible Fats And Oils,N.E.C.'),
	 ('Blankbooks And Looseleaf Binders'),
	 ('Electrical Industrial Apparatus, N.E.C.'),
	 ('Paper Coated & Laminated, Packaging') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Flavoring Extracts And Syrups, N.E.C.'),
	 ('Broadwoven Fabric Mills, Man Made Fiber & Silk'),
	 ('Fluid Power Valves & Hose Fittings'),
	 ('Chemicals & Allied Products'),
	 ('Manifold Business Forms'),
	 ('Special Industry Machinery, Nec'),
	 ('Structural Steel Erection'),
	 ('Softwood Veneer And Plywood'),
	 ('Glass Products, Made Of Purchased Glass'),
	 ('Retail-Drug Stores And Proprietary Stores') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Lighting Equipment, N.E.C.'),
	 ('Carbon Black'),
	 ('Wholesale Trade-Nondurable Goods'),
	 ('Industrial Valves'),
	 ('Electric Lighting & Wiring Equipment'),
	 ('Pipe Lines (No Natural Gas)'),
	 ('Computer Maintenance & Repair'),
	 ('Furniture And Fixtures, N.E.C.'),
	 ('Fabric Dress And Work Gloves'),
	 ('Leather & Leather Products') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Retail-Building Materials, Hardware, Garden Supply'),
	 ('Crushed And Broken Stone, N.E.C.'),
	 ('Wine And Distilled Beverages'),
	 ('Ice Cream & Frozen Desserts'),
	 ('Wholesale-Groceries, General Line'),
	 ('Abrasive Products'),
	 ('Retail-Shoe Stores'),
	 ('Retail-Eating Places'),
	 ('General Automotive Repair Shops'),
	 ('Machine Tool Accessories') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Asphalt Felts And Coatings'),
	 ('Industrial & Personal Service Paper'),
	 ('Chocolate And Cocoa Products'),
	 ('Metal Cans'),
	 ('Finishing Plants, Manmade'),
	 ('Wood Partitions And Fixtures'),
	 ('Cellulosic Manmade Fibers'),
	 ('Women''S And Misses'' Outerwear, N.E.C.'),
	 ('Personal Credit Institutions'),
	 ('Plumbing & Hydronic Heating Supplies') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Laundry, Cleaning, & Garment Services'),
	 ('Roofing, Siding, & Insulation'),
	 ('Airports, Flying Fields & Airport Terminal Services'),
	 ('Services-Facilities Support Management Services'),
	 ('Motorcycles, Bicycles, And Parts'),
	 ('Museums And Art Galleries'),
	 ('Automobiles And Other Motor Vehicles'),
	 ('Water Transportation Services, N.E.C.'),
	 ('Flowers & Florists'' Supplies'),
	 ('Short-Term Business Credit Institutions') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Primary Production Of Aluminum'),
	 ('Heavy Construction Other Than Bldg Const - Contractors'),
	 ('Radio And Television Broadcasting'),
	 ('Office Equipment'),
	 ('Dairy Products Stores'),
	 ('Finance Lessors'),
	 ('Miscellaneous Nonmetallic Minerals'),
	 ('Metal Cans And Shipping Containers'),
	 ('Services-Misc Health & Allied Services, Nec'),
	 ('Pension, Health, And Welfare Funds') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Beverages'),
	 ('Oil And Gas Field Services'),
	 ('Trucking Terminal Facilities'),
	 ('Eating And Drinking Places'),
	 ('Special Industry Machinery (No Metalworking Machinery)'),
	 ('Women''S, Misses'', And Juniors Outerwear'),
	 ('Passenger Transportation Arrangement'),
	 ('Fabricated Structural Metal Products'),
	 ('Communication Services, N.E.C.'),
	 ('Medical And Dental Laboratories') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Wholesale-Machinery, Equipment & Supplies'),
	 ('Construction, Mining & Materials Handling Machinery & Equip'),
	 ('Wood Buildings And Mobile Homes'),
	 ('Luggage'),
	 ('Industrial Organic Chemicals'),
	 ('Anthracite Mining'),
	 ('Membership Organizations, N.E.C.'),
	 ('Miscellaneous Transportation Equipment'),
	 ('Deep Sea Foreign Trans. Of Freight'),
	 ('Structural Clay Products') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Concrete Work'),
	 ('Misc. Special Trade Contractors'),
	 ('Automotive Dealers, N.E.C'),
	 ('Barber Shops'),
	 ('Miscellaneous Apparel And Accessories'),
	 ('Fruit And Vegetable Markets'),
	 ('Products Of Purchased Glass'),
	 ('Hazardous Waste Management'),
	 ('Retail Bakeries'),
	 ('Textile Finishing, Except Wool') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Wood Containers'),
	 ('Retail-Miscellaneous Shopping Goods Stores'),
	 ('Fabricated Rubber Products, Nec'),
	 ('Wholesale-Metals & Minerals (No Petroleum)'),
	 ('Iron Ores'),
	 ('Tobacco Products'),
	 ('Electric Distribution Equipment'),
	 ('Schiffli Machine Embroideries'),
	 ('Motion Pictures'),
	 ('Periodicals') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Narrow Fabric Mills'),
	 ('Commercial Sports'),
	 ('Girls'' And Children''S Outerwear'),
	 ('Offices And Clinics Of Dentists'),
	 ('Wholesale-Apparel, Piece Goods & Notions'),
	 ('Toys And Sporting Goods'),
	 ('Iron & Steel Foundries'),
	 ('Miscellaneous Textile Goods'),
	 ('Motor Vehicles And Equipment'),
	 ('Newspapers') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Men''S & Boys'' Furnishgs, Work Clothg, & Allied Garments'),
	 ('Water Transportation Services'),
	 ('Services-Miscellaneous Repair Services'),
	 ('Abrasive, Asbestos & Misc Nonmetallic Mineral Prods'),
	 ('Retail-Retail Stores, Nec'),
	 ('Federal & Fed.-Sponsored Credit'),
	 ('Steel Works, Blast Furnaces & Rolling & Finishing Mills'),
	 ('Yarn And Thread Mills'),
	 ('Fats & Oils'),
	 ('Millwood, Veneer, Plywood, & Structural Wood Members') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Bituminous Coal And Lignite Mining'),
	 ('Drug Stores And Proprietary Stores'),
	 ('Coating, Engraving & Allied Services'),
	 ('Radio, Television, & Computer Stores'),
	 ('Services-Miscellaneous Equipment Rental & Leasing'),
	 ('General Bldg Contractors - Nonresidential Bldgs'),
	 ('Gaskets, Packg & Sealg Devices & Rubber & Plastics Hose'),
	 ('Shoe Stores'),
	 ('Services-Nursing & Personal Care Facilities'),
	 ('Variety Stores') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('General Industrial Machinery & Equipment'),
	 ('Agr Administrative And Auxiliary'),
	 ('Retail-Eating & Drinking Places'),
	 ('Wholesale-Furniture & Home Furnishings'),
	 ('Sugar & Confectionery Products'),
	 ('Automotive Repair Shops'),
	 ('Business Credit Institutions'),
	 ('Meat And Fish Markets'),
	 ('Women''S, Misses'', Children''S & Infants'' Undergarments'),
	 ('Meat Products') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Freight Trans. On The Great Lakes'),
	 ('Leather Goods, N.E.C.'),
	 ('Watch, Clock, And Jewelry Repair'),
	 ('Wholesale-Paper & Paper Products'),
	 ('Public Building & Related Furniture'),
	 ('Hardware Stores'),
	 ('Automotive Services, Except Repair'),
	 ('Medical Service And Health Insurance'),
	 ('Fuel Dealers'),
	 ('Cogeneration Services & Small Power Producers') on conflict do nothing;
INSERT INTO public.zi_industry (value) VALUES
	 ('Medical Instruments And Supplies'),
	 ('Screw Machine Products, Bolts, Etc.'),
	 ('Grain Mill Products'),
	 ('Miscellaneous Personal Services'),
	 ('Central Reserve Depository'),
	 ('Miscellaneous Chemical Products'),
	 ('Sawmills And Planing Mills'),
	 ('Job Training And Related Services'),
	 ('Wholesale-Misc Durable Goods') on conflict do nothing;

-- zi_seniority
-- 
INSERT INTO public.zi_seniority (value) VALUES
	 ('Manager'),
	 ('Cxo'),
	 ('Director'),
	 ('Staff'),
	 ('Vp') on conflict do nothing;

-- zi_sic
-- 
INSERT INTO public.zi_sic (value) VALUES
	 ('4924'),
	 ('8742'),
	 ('5012'),
	 ('3542'),
	 ('2111'),
	 ('2499'),
	 ('1320'),
	 ('6794'),
	 ('3465'),
	 ('8082') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('8071'),
	 ('7832'),
	 ('2252'),
	 ('5300'),
	 ('3845'),
	 ('3596'),
	 ('5500'),
	 ('3996'),
	 ('7320'),
	 ('7218') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2731'),
	 ('8042'),
	 ('8093'),
	 ('2262'),
	 ('2891'),
	 ('2393'),
	 ('2675'),
	 ('5137'),
	 ('1794'),
	 ('7996') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('7352'),
	 ('3576'),
	 ('3011'),
	 ('3087'),
	 ('4226'),
	 ('7323'),
	 ('2835'),
	 ('3861'),
	 ('7349'),
	 ('5021') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2200'),
	 ('2281'),
	 ('7537'),
	 ('3443'),
	 ('2610'),
	 ('3339'),
	 ('7381'),
	 ('2816'),
	 ('3462'),
	 ('4832') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3952'),
	 ('3356'),
	 ('3555'),
	 ('3000'),
	 ('5946'),
	 ('7335'),
	 ('4941'),
	 ('5136'),
	 ('1752'),
	 ('4961') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3511'),
	 ('3577'),
	 ('6700'),
	 ('7363'),
	 ('5153'),
	 ('3541'),
	 ('2800'),
	 ('3365'),
	 ('3491'),
	 ('3825') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3330'),
	 ('2621'),
	 ('7372'),
	 ('4500'),
	 ('3080'),
	 ('3795'),
	 ('2841'),
	 ('1795'),
	 ('3544'),
	 ('3711') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2833'),
	 ('5082'),
	 ('1600'),
	 ('2026'),
	 ('1420'),
	 ('5031'),
	 ('5139'),
	 ('3949'),
	 ('2676'),
	 ('2000') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3334'),
	 ('3643'),
	 ('3463'),
	 ('2844'),
	 ('3647'),
	 ('3253'),
	 ('7542'),
	 ('5412'),
	 ('8711'),
	 ('3533') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2258'),
	 ('3822'),
	 ('2512'),
	 ('3353'),
	 ('2062'),
	 ('5700'),
	 ('4812'),
	 ('5092'),
	 ('7370'),
	 ('2434') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3740'),
	 ('2075'),
	 ('1060'),
	 ('4822'),
	 ('6111'),
	 ('7230'),
	 ('5993'),
	 ('3652'),
	 ('1020'),
	 ('7384') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3399'),
	 ('5000'),
	 ('3564'),
	 ('8640'),
	 ('5920'),
	 ('3452'),
	 ('3826'),
	 ('4489'),
	 ('3444'),
	 ('7993') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4939'),
	 ('2531'),
	 ('3523'),
	 ('3635'),
	 ('3953'),
	 ('6553'),
	 ('5051'),
	 ('2337'),
	 ('5085'),
	 ('5091') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3259'),
	 ('7382'),
	 ('4222'),
	 ('3351'),
	 ('4000'),
	 ('7217'),
	 ('7820'),
	 ('2120'),
	 ('2269'),
	 ('7536') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1382'),
	 ('3315'),
	 ('7200'),
	 ('2250'),
	 ('7250'),
	 ('2752'),
	 ('3678'),
	 ('2678'),
	 ('8720'),
	 ('2514') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('6720'),
	 ('2522'),
	 ('1400'),
	 ('1422'),
	 ('2110'),
	 ('7219'),
	 ('6732'),
	 ('3625'),
	 ('3489'),
	 ('3547') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2096'),
	 ('3575'),
	 ('6519'),
	 ('7291'),
	 ('1741'),
	 ('2830'),
	 ('8740'),
	 ('8051'),
	 ('2253'),
	 ('3390') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2812'),
	 ('5078'),
	 ('8060'),
	 ('8734'),
	 ('2429'),
	 ('3955'),
	 ('7941'),
	 ('2086'),
	 ('7385'),
	 ('2653') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('8743'),
	 ('2085'),
	 ('2652'),
	 ('2051'),
	 ('3566'),
	 ('3639'),
	 ('1479'),
	 ('2064'),
	 ('6221'),
	 ('5960') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2823'),
	 ('1700'),
	 ('7819'),
	 ('6350'),
	 ('2741'),
	 ('5182'),
	 ('2449'),
	 ('5714'),
	 ('4729'),
	 ('0900') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4841'),
	 ('3264'),
	 ('2053'),
	 ('2038'),
	 ('1742'),
	 ('7211'),
	 ('2341'),
	 ('4142'),
	 ('2834'),
	 ('2426') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2011'),
	 ('7389'),
	 ('3545'),
	 ('7699'),
	 ('3563'),
	 ('3082'),
	 ('2020'),
	 ('2515'),
	 ('5736'),
	 ('3446') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2391'),
	 ('3645'),
	 ('3716'),
	 ('7213'),
	 ('3421'),
	 ('8049'),
	 ('4923'),
	 ('2911'),
	 ('2790'),
	 ('3519') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('8300'),
	 ('3674'),
	 ('2760'),
	 ('3400'),
	 ('7313'),
	 ('7011'),
	 ('5943'),
	 ('5945'),
	 ('3821'),
	 ('2083') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2410'),
	 ('2024'),
	 ('1300'),
	 ('4813'),
	 ('8730'),
	 ('3291'),
	 ('2251'),
	 ('3691'),
	 ('3271'),
	 ('3483') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1040'),
	 ('8990'),
	 ('3469'),
	 ('4213'),
	 ('2789'),
	 ('3644'),
	 ('6162'),
	 ('7997'),
	 ('3578'),
	 ('1389') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3269'),
	 ('8041'),
	 ('5620'),
	 ('8010'),
	 ('3261'),
	 ('1520'),
	 ('8748'),
	 ('7922'),
	 ('3824'),
	 ('2013') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2045'),
	 ('3944'),
	 ('2396'),
	 ('2900'),
	 ('4930'),
	 ('8043'),
	 ('3660'),
	 ('3366'),
	 ('5099'),
	 ('1480') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('6792'),
	 ('3942'),
	 ('3677'),
	 ('8733'),
	 ('3499'),
	 ('2655'),
	 ('7812'),
	 ('3570'),
	 ('3412'),
	 ('3582') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2091'),
	 ('4141'),
	 ('2384'),
	 ('6510'),
	 ('2331'),
	 ('3493'),
	 ('3843'),
	 ('3632'),
	 ('2421'),
	 ('5271') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3915'),
	 ('3761'),
	 ('2033'),
	 ('3620'),
	 ('2861'),
	 ('3313'),
	 ('3732'),
	 ('6411'),
	 ('2063'),
	 ('4953') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3355'),
	 ('5961'),
	 ('3088'),
	 ('4810'),
	 ('3679'),
	 ('3556'),
	 ('5999'),
	 ('1751'),
	 ('2342'),
	 ('5074') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1000'),
	 ('3360'),
	 ('6324'),
	 ('1090'),
	 ('2796'),
	 ('1459'),
	 ('2754'),
	 ('4724'),
	 ('5169'),
	 ('7210') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2879'),
	 ('2892'),
	 ('7334'),
	 ('2822'),
	 ('8650'),
	 ('3931'),
	 ('3552'),
	 ('3599'),
	 ('1793'),
	 ('3648') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3451'),
	 ('3548'),
	 ('6552'),
	 ('0761'),
	 ('3676'),
	 ('5052'),
	 ('4481'),
	 ('7810'),
	 ('3299'),
	 ('3221') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5992'),
	 ('4820'),
	 ('3594'),
	 ('2385'),
	 ('3671'),
	 ('3081'),
	 ('5040'),
	 ('3143'),
	 ('3700'),
	 ('3695') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4899'),
	 ('7360'),
	 ('7374'),
	 ('2076'),
	 ('1610'),
	 ('3069'),
	 ('3743'),
	 ('3565'),
	 ('2899'),
	 ('2541') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5064'),
	 ('3630'),
	 ('4610'),
	 ('0700'),
	 ('3431'),
	 ('3751'),
	 ('4221'),
	 ('5198'),
	 ('7377'),
	 ('0762') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2321'),
	 ('4225'),
	 ('3398'),
	 ('3999'),
	 ('2220'),
	 ('2044'),
	 ('5400'),
	 ('5044'),
	 ('2210'),
	 ('4400') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3633'),
	 ('2451'),
	 ('2361'),
	 ('4800'),
	 ('2386'),
	 ('5193'),
	 ('3651'),
	 ('3728'),
	 ('1442'),
	 ('3991') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3341'),
	 ('2600'),
	 ('1791'),
	 ('1720'),
	 ('4440'),
	 ('7312'),
	 ('2023'),
	 ('2035'),
	 ('2022'),
	 ('PRIMARY_SIC') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5014'),
	 ('8900'),
	 ('2257'),
	 ('5230'),
	 ('3460'),
	 ('3993'),
	 ('3274'),
	 ('2910'),
	 ('7300'),
	 ('8410') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4210'),
	 ('8220'),
	 ('2099'),
	 ('4522'),
	 ('6300'),
	 ('0200'),
	 ('5063'),
	 ('7322'),
	 ('5111'),
	 ('5941') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3296'),
	 ('3569'),
	 ('3241'),
	 ('0100'),
	 ('5812'),
	 ('3715'),
	 ('2325'),
	 ('2066'),
	 ('5146'),
	 ('1760') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('7331'),
	 ('3340'),
	 ('3524'),
	 ('6331'),
	 ('2491'),
	 ('3540'),
	 ('3130'),
	 ('2510'),
	 ('3357'),
	 ('3220') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2052'),
	 ('2517'),
	 ('2381'),
	 ('3841'),
	 ('2631'),
	 ('3554'),
	 ('3262'),
	 ('1221'),
	 ('3873'),
	 ('3562') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1200'),
	 ('1094'),
	 ('5399'),
	 ('7336'),
	 ('2296'),
	 ('8111'),
	 ('2869'),
	 ('3593'),
	 ('2098'),
	 ('5211') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2819'),
	 ('6531'),
	 ('3086'),
	 ('5122'),
	 ('1799'),
	 ('2591'),
	 ('1620'),
	 ('3171'),
	 ('3423'),
	 ('3425') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3300'),
	 ('3149'),
	 ('3553'),
	 ('2673'),
	 ('3061'),
	 ('7376'),
	 ('6200'),
	 ('5140'),
	 ('7948'),
	 ('3641') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3520'),
	 ('2261'),
	 ('7319'),
	 ('2999'),
	 ('7900'),
	 ('4482'),
	 ('3471'),
	 ('3411'),
	 ('4110'),
	 ('7629') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3430'),
	 ('2074'),
	 ('6060'),
	 ('0800'),
	 ('5948'),
	 ('6351'),
	 ('4950'),
	 ('5048'),
	 ('0720'),
	 ('4920') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2284'),
	 ('2732'),
	 ('2500'),
	 ('8100'),
	 ('8200'),
	 ('3646'),
	 ('5049'),
	 ('2394'),
	 ('5731'),
	 ('7216') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5192'),
	 ('7692'),
	 ('5084'),
	 ('3634'),
	 ('2297'),
	 ('6311'),
	 ('3764'),
	 ('3769'),
	 ('6211'),
	 ('5180') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1220'),
	 ('1446'),
	 ('2221'),
	 ('2436'),
	 ('6035'),
	 ('5047'),
	 ('3020'),
	 ('3325'),
	 ('7829'),
	 ('2130') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5100'),
	 ('5944'),
	 ('5984'),
	 ('3089'),
	 ('8888'),
	 ('3272'),
	 ('5010'),
	 ('3675'),
	 ('2865'),
	 ('5013') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2599'),
	 ('0760'),
	 ('7375'),
	 ('5093'),
	 ('7533'),
	 ('2611'),
	 ('2015'),
	 ('1455'),
	 ('6399'),
	 ('4499') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2043'),
	 ('2782'),
	 ('2048'),
	 ('5311'),
	 ('5142'),
	 ('2079'),
	 ('3965'),
	 ('2082'),
	 ('5072'),
	 ('2895') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('7623'),
	 ('2656'),
	 ('4940'),
	 ('3536'),
	 ('9721'),
	 ('2874'),
	 ('2875'),
	 ('3369'),
	 ('7513'),
	 ('2671') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5995'),
	 ('2067'),
	 ('2842'),
	 ('3535'),
	 ('3210'),
	 ('7371'),
	 ('3585'),
	 ('2140'),
	 ('3497'),
	 ('2392') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3295'),
	 ('5046'),
	 ('3251'),
	 ('2339'),
	 ('1531'),
	 ('2097'),
	 ('6141'),
	 ('3995'),
	 ('2034'),
	 ('5149') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4619'),
	 ('4931'),
	 ('7549'),
	 ('7538'),
	 ('3914'),
	 ('5039'),
	 ('0750'),
	 ('5141'),
	 ('6400'),
	 ('2259') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3053'),
	 ('3500'),
	 ('1240'),
	 ('2282'),
	 ('3612'),
	 ('1750'),
	 ('2395'),
	 ('6163'),
	 ('3494'),
	 ('2211') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2295'),
	 ('4581'),
	 ('8000'),
	 ('4492'),
	 ('3911'),
	 ('7373'),
	 ('3441'),
	 ('3581'),
	 ('7519'),
	 ('3714') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('7000'),
	 ('2952'),
	 ('8710'),
	 ('3669'),
	 ('8400'),
	 ('1474'),
	 ('7260'),
	 ('2520'),
	 ('2087'),
	 ('3629') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3273'),
	 ('6798'),
	 ('4013'),
	 ('3561'),
	 ('7515'),
	 ('6799'),
	 ('2672'),
	 ('6361'),
	 ('5651'),
	 ('5190') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4512'),
	 ('2674'),
	 ('6022'),
	 ('2046'),
	 ('3546'),
	 ('3720'),
	 ('2851'),
	 ('5144'),
	 ('7215'),
	 ('7534') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1041'),
	 ('2821'),
	 ('7510'),
	 ('0780'),
	 ('3672'),
	 ('4731'),
	 ('3010'),
	 ('7359'),
	 ('7379'),
	 ('7999') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1710'),
	 ('5045'),
	 ('3144'),
	 ('2090'),
	 ('5070'),
	 ('2092'),
	 ('3799'),
	 ('5813'),
	 ('1500'),
	 ('2519') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3322'),
	 ('7532'),
	 ('8072'),
	 ('7500'),
	 ('5159'),
	 ('5043'),
	 ('1440'),
	 ('6500'),
	 ('5989'),
	 ('7342') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4200'),
	 ('2542'),
	 ('3466'),
	 ('5734'),
	 ('7378'),
	 ('3543'),
	 ('2761'),
	 ('4600'),
	 ('8030'),
	 ('3592') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2322'),
	 ('5087'),
	 ('3823'),
	 ('3482'),
	 ('5112'),
	 ('4493'),
	 ('9900'),
	 ('3842'),
	 ('5719'),
	 ('8210') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2323'),
	 ('2493'),
	 ('3363'),
	 ('2387'),
	 ('1475'),
	 ('5088'),
	 ('3433'),
	 ('1311'),
	 ('8062'),
	 ('8744') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5015'),
	 ('3172'),
	 ('7220'),
	 ('2400'),
	 ('4231'),
	 ('3699'),
	 ('3990'),
	 ('3800'),
	 ('1623'),
	 ('3312') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1743'),
	 ('3663'),
	 ('2992'),
	 ('2850'),
	 ('2759'),
	 ('2441'),
	 ('6330'),
	 ('7622'),
	 ('4111'),
	 ('1780') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5661'),
	 ('5162'),
	 ('3449'),
	 ('2711'),
	 ('8600'),
	 ('5531'),
	 ('2870'),
	 ('5083'),
	 ('5713'),
	 ('5994') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3496'),
	 ('3317'),
	 ('1310'),
	 ('3263'),
	 ('3429'),
	 ('3100'),
	 ('1450'),
	 ('6532'),
	 ('5172'),
	 ('7330') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2452'),
	 ('5942'),
	 ('2730'),
	 ('2813'),
	 ('3492'),
	 ('2300'),
	 ('6282'),
	 ('3589'),
	 ('0710'),
	 ('3694') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4725'),
	 ('3724'),
	 ('2032'),
	 ('7361'),
	 ('4700'),
	 ('7033'),
	 ('2951'),
	 ('5200'),
	 ('3484'),
	 ('2335') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3142'),
	 ('5148'),
	 ('7833'),
	 ('3354'),
	 ('3084'),
	 ('3448'),
	 ('3316'),
	 ('7620'),
	 ('5962'),
	 ('3442') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3021'),
	 ('3624'),
	 ('4900'),
	 ('3432'),
	 ('4922'),
	 ('6099'),
	 ('7311'),
	 ('5949'),
	 ('5900'),
	 ('5023') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('6020'),
	 ('3231'),
	 ('2439'),
	 ('5411'),
	 ('2084'),
	 ('3731'),
	 ('6153'),
	 ('8731'),
	 ('2047'),
	 ('2836') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('7991'),
	 ('6100'),
	 ('2590'),
	 ('6321'),
	 ('3750'),
	 ('1423'),
	 ('3480'),
	 ('7822'),
	 ('2399'),
	 ('3140') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2350'),
	 ('5710'),
	 ('3571'),
	 ('2657'),
	 ('4911'),
	 ('2230'),
	 ('5963'),
	 ('2770'),
	 ('7539'),
	 ('3085') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2095'),
	 ('3692'),
	 ('2873'),
	 ('2677'),
	 ('3549'),
	 ('8700'),
	 ('7514'),
	 ('1222'),
	 ('3052'),
	 ('2435') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5191'),
	 ('8351'),
	 ('3364'),
	 ('5113'),
	 ('2329'),
	 ('2448'),
	 ('2037'),
	 ('1381'),
	 ('3211'),
	 ('3640') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('8712'),
	 ('2254'),
	 ('3532'),
	 ('3255'),
	 ('3200'),
	 ('2299'),
	 ('6512'),
	 ('2298'),
	 ('5033'),
	 ('1044') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1429'),
	 ('2041'),
	 ('3721'),
	 ('5075'),
	 ('7520'),
	 ('7929'),
	 ('3083'),
	 ('7032'),
	 ('3827'),
	 ('4412') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1731'),
	 ('2389'),
	 ('5194'),
	 ('7212'),
	 ('2750'),
	 ('3579'),
	 ('3229'),
	 ('7841'),
	 ('2630'),
	 ('2431') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5181'),
	 ('5032'),
	 ('3324'),
	 ('5735'),
	 ('6036'),
	 ('5143'),
	 ('3537'),
	 ('3498'),
	 ('2511'),
	 ('3670') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3495'),
	 ('4119'),
	 ('7383'),
	 ('6021'),
	 ('6550'),
	 ('3650'),
	 ('1730'),
	 ('3961'),
	 ('3534'),
	 ('7299') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5154'),
	 ('2824'),
	 ('5530'),
	 ('3260'),
	 ('7338'),
	 ('5065'),
	 ('2540'),
	 ('2030'),
	 ('3792'),
	 ('4100') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('6733'),
	 ('4011'),
	 ('7353'),
	 ('5150'),
	 ('2893'),
	 ('5600'),
	 ('3568'),
	 ('6029'),
	 ('3580'),
	 ('3531') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1030'),
	 ('3851'),
	 ('3292'),
	 ('2326'),
	 ('5912'),
	 ('3713'),
	 ('3510'),
	 ('5147'),
	 ('7694'),
	 ('2771') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4513'),
	 ('2369'),
	 ('8011'),
	 ('3661'),
	 ('5199'),
	 ('1080'),
	 ('2021'),
	 ('4830'),
	 ('2521'),
	 ('3567') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3600'),
	 ('4491'),
	 ('5983'),
	 ('3275'),
	 ('3621'),
	 ('8290'),
	 ('8741'),
	 ('2061'),
	 ('2843'),
	 ('3572') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3613'),
	 ('8732'),
	 ('3297'),
	 ('5331'),
	 ('2068'),
	 ('2050'),
	 ('6159'),
	 ('3270'),
	 ('8713'),
	 ('7310') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3281'),
	 ('3331'),
	 ('5947'),
	 ('5131'),
	 ('2820'),
	 ('2721'),
	 ('3812'),
	 ('3631'),
	 ('1796'),
	 ('7992') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2077'),
	 ('2273'),
	 ('5171'),
	 ('3280'),
	 ('5712'),
	 ('7020'),
	 ('5145'),
	 ('3586'),
	 ('4833'),
	 ('2700') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3321'),
	 ('3829'),
	 ('7830'),
	 ('3559'),
	 ('6000'),
	 ('3844'),
	 ('2791'),
	 ('5621'),
	 ('3479'),
	 ('3951') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4932'),
	 ('6199'),
	 ('5094'),
	 ('5540'),
	 ('5510'),
	 ('1740'),
	 ('2679'),
	 ('6513'),
	 ('1490'),
	 ('5450') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4520'),
	 ('8070'),
	 ('6370'),
	 ('1380'),
	 ('3550'),
	 ('4890'),
	 ('4230'),
	 ('3440'),
	 ('5800'),
	 ('3530') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5080'),
	 ('2330'),
	 ('6172'),
	 ('4720'),
	 ('3410'),
	 ('2080'),
	 ('8090'),
	 ('8690'),
	 ('2380'),
	 ('5590') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('1790'),
	 ('3160'),
	 ('3790'),
	 ('4410'),
	 ('7240'),
	 ('1230'),
	 ('2860'),
	 ('3250'),
	 ('1770'),
	 ('2450') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3060'),
	 ('5940'),
	 ('2260'),
	 ('2740'),
	 ('3230'),
	 ('3900'),
	 ('5430'),
	 ('1010'),
	 ('4955'),
	 ('4910') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('5460'),
	 ('1530'),
	 ('3930'),
	 ('5050'),
	 ('2440'),
	 ('2720'),
	 ('2100'),
	 ('2397'),
	 ('7800'),
	 ('2240') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('7940'),
	 ('3610'),
	 ('2290'),
	 ('5130'),
	 ('2360'),
	 ('3940'),
	 ('3320'),
	 ('3710'),
	 ('8020'),
	 ('2710') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2320'),
	 ('4490'),
	 ('7600'),
	 ('3290'),
	 ('6110'),
	 ('5990'),
	 ('2280'),
	 ('6310'),
	 ('3310'),
	 ('5910') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2430'),
	 ('2070'),
	 ('3470'),
	 ('5730'),
	 ('7350'),
	 ('1540'),
	 ('5660'),
	 ('3050'),
	 ('5330'),
	 ('8050') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('3560'),
	 ('0980'),
	 ('5810'),
	 ('3240'),
	 ('5020'),
	 ('2060'),
	 ('7530'),
	 ('2010'),
	 ('5420'),
	 ('6150') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('2340'),
	 ('4430'),
	 ('3190'),
	 ('5110'),
	 ('7630'),
	 ('2530'),
	 ('5250'),
	 ('7540'),
	 ('6320'),
	 ('5980') on conflict do nothing;
INSERT INTO public.zi_sic (value) VALUES
	 ('4991'),
	 ('3840'),
	 ('3450'),
	 ('2040'),
	 ('7290'),
	 ('6010'),
	 ('2890'),
	 ('2420'),
	 ('8330'),
	 ('5090') on conflict do nothing;
